[package]
name = "rltk-app"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rltk-app"

[dependencies]
rltk = "0.8"
specs = "0.17"
specs-derive = "0.4"
